/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

/**
 *
 * @author angel_rodriguez
 */
public class Vista extends javax.swing.JFrame {
    
    Controlador controlador;
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfHospital = new javax.swing.JTextField();
        tfUnidad = new javax.swing.JTextField();
        tfPlanta = new javax.swing.JTextField();
        tfPersonal = new javax.swing.JTextField();
        btnSiguienteUnidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hospital:");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Personal:");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Planta:");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Unidad:");

        tfHospital.setBackground(new java.awt.Color(255, 255, 255));
        tfHospital.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        tfHospital.setForeground(new java.awt.Color(0, 0, 0));
        tfHospital.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHospitalActionPerformed(evt);
            }
        });

        tfUnidad.setBackground(new java.awt.Color(255, 255, 255));
        tfUnidad.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        tfUnidad.setForeground(new java.awt.Color(0, 0, 0));
        tfUnidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnidadActionPerformed(evt);
            }
        });

        tfPlanta.setBackground(new java.awt.Color(255, 255, 255));
        tfPlanta.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        tfPlanta.setForeground(new java.awt.Color(0, 0, 0));
        tfPlanta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPlantaActionPerformed(evt);
            }
        });

        tfPersonal.setBackground(new java.awt.Color(255, 255, 255));
        tfPersonal.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        tfPersonal.setForeground(new java.awt.Color(0, 0, 0));
        tfPersonal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPersonalActionPerformed(evt);
            }
        });

        btnSiguienteUnidad.setBackground(new java.awt.Color(153, 204, 255));
        btnSiguienteUnidad.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        btnSiguienteUnidad.setForeground(new java.awt.Color(0, 0, 0));
        btnSiguienteUnidad.setText("Siguiente Unidad ");
        btnSiguienteUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteUnidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSiguienteUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tfHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(tfUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(tfPlanta)
                    .addComponent(tfPersonal))
                .addGap(18, 18, 18)
                .addComponent(btnSiguienteUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHospitalActionPerformed

    private void tfUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnidadActionPerformed

    private void tfPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPlantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPlantaActionPerformed

    private void tfPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPersonalActionPerformed

    private void btnSiguienteUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteUnidadActionPerformed
        controlador.siguiente();
    }//GEN-LAST:event_btnSiguienteUnidadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguienteUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfHospital;
    private javax.swing.JTextField tfPersonal;
    private javax.swing.JTextField tfPlanta;
    private javax.swing.JTextField tfUnidad;
    // End of variables declaration//GEN-END:variables

    public void actualizarVista(Unidad unidad){
        this.tfHospital.setText(controlador.getHospital().getNombre());
        this.tfUnidad.setText(unidad.getTipo());
        this.tfPlanta.setText(String.valueOf(unidad.getPlanta()));
        this.tfPersonal.setText(String.valueOf(unidad.personal()));
        
        super.repaint();
        super.revalidate();        
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    
}
