
package vista;

import controlador.Controlador;
import modelo.Parcela;
import modelo.Soja;
import modelo.TipoCultivo;
import modelo.Trigo;
import java.awt.Color;
import java.util.ArrayList;
import modelo.Cultivo;


/**
 *
 * @author angel_rodriguez
 */
public class VistaPrincipal extends javax.swing.JFrame implements IVista{
    //-------------------------------------------------
    // Atributos
    //-------------------------------------------------
    private ArrayList<VistaParcela> vistaParcelas = new ArrayList<>();
    
    //-------------------------------------------------
    // Constructores
    //-------------------------------------------------
    public VistaPrincipal() {
        initComponents();
        panelMapa.setBackground(new Color(255, 255, 255, 0)); 
        setVisible(true);
    }
    
    //-------------------------------------------------
    // Funciones
    //-------------------------------------------------
    public void inicializarVista(){
        for(Parcela parcela : Controlador.instancia.getParcelas()){
            addParcela(parcela);   
        }
    }
    
    public void mostrarVista () {
        this.setVisible(true);
    }

    public void actualizarVista() {
        this.lbNumExp.setText(String.valueOf(Controlador.instancia.getNivel()));
        
         
        // ----
        // EXAMEN
        // TODO Completa el método actualizarVista para mostrar el dinero del juego.
        this.lbDinero.setText(String.valueOf(Controlador.instancia.getDinero()));
                
        // TODO Complete el método actualizarVista para mostrar la experiencia del juego en la barra de experiencia.
        this.pbExp.setValue(Controlador.instancia.getExperiencia());
        
        // TODO Complete el método actualizarVista para cambiar el texto del precio de venta del trigo y de la soja
        this.lbPrecioVentaTrigo.setText(String.valueOf(Trigo.PRECIO_VENTA));
        this.lbPrecioVentaSoja.setText(String.valueOf(Soja.PRECIO_VENTA));
        
         // FIN DE EXAMEN
        // ---- 
                
        this.pbExp.setMaximum(Controlador.instancia.getProgresoActual());
        this.lbNumLevelsExp.setText(String.valueOf(Controlador.instancia.getExperiencia()));
        this.lbNumLevelsExp.setText(String.valueOf(Controlador.instancia.getExperiencia()) + "/" +Controlador.instancia.getProgresoActual());
        this.lbNumTrigo.setText(String.valueOf(Controlador.instancia.getCultivosDisponiblesDeUnTipo(TipoCultivo.TRIGO)));
        this.lbNumSoja.setText(String.valueOf(Controlador.instancia.getCultivosDisponiblesDeUnTipo(TipoCultivo.SOJA)));
        
        this.lbPrecioCompraParcela.setText(String.valueOf(Parcela.PRECIO));
        this.btnComprarParcela.setEnabled(Controlador.instancia.getDinero() - 15 >= 0);
        

        this.btnVenderTrigo.setEnabled(Controlador.instancia.getCultivosDisponiblesDeUnTipo(TipoCultivo.TRIGO) > 0);
        this.btnVenderSoja.setEnabled(Controlador.instancia.getCultivosDisponiblesDeUnTipo(TipoCultivo.SOJA) > 0);

        
         for(VistaParcela pv: vistaParcelas){
            pv.setVisible(true);
            pv.actualizarVista();
        }
        
        repaint();
        revalidate();
    }
    
    private void addParcela(Parcela p){
        VistaParcela pv = new VistaParcela(p);
        vistaParcelas.add(pv);
        panelMapa.add(pv);
        pv.actualizarVista();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabecera = new javax.swing.JPanel();
        lbLogoHayDay = new javax.swing.JLabel();
        lbDinero = new javax.swing.JLabel();
        panelComprarParcela = new javax.swing.JPanel();
        lbDineroParcela = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbPrecioCompraParcela = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnComprarParcela = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelVenderTrigo = new javax.swing.JPanel();
        lbDineroTrigo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbPrecioVentaTrigo = new javax.swing.JLabel();
        btnVenderTrigo = new javax.swing.JButton();
        panelVenderSoja = new javax.swing.JPanel();
        lbDineroSoja = new javax.swing.JLabel();
        btnVenderSoja = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbPrecioVentaSoja = new javax.swing.JLabel();
        panelProductos = new javax.swing.JPanel();
        lbIconoTrigo = new javax.swing.JLabel();
        lbNumTrigo = new javax.swing.JLabel();
        lbNumSoja = new javax.swing.JLabel();
        lbIconoSoja = new javax.swing.JLabel();
        pbExp = new javax.swing.JProgressBar();
        lbNumLevelsExp = new javax.swing.JLabel();
        lbIconExp = new javax.swing.JLabel();
        lbExp = new javax.swing.JLabel();
        lbNumExp = new javax.swing.JLabel();
        panelCampo = new javax.swing.JPanel();
        panelMapa = new javax.swing.JPanel();
        lbHierba = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCabecera.setBackground(new java.awt.Color(240, 177, 38));

        lbLogoHayDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hayday.jpg"))); // NOI18N
        lbLogoHayDay.setText("\n");

        lbDinero.setFont(new java.awt.Font("Yrsa SemiBold", 1, 36)); // NOI18N
        lbDinero.setForeground(new java.awt.Color(255, 255, 255));
        lbDinero.setText("0\n");

        panelComprarParcela.setBackground(new java.awt.Color(241, 176, 46));
        panelComprarParcela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbDineroParcela.setForeground(new java.awt.Color(0, 0, 0));
        lbDineroParcela.setText("PARCELA");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parcela64.png"))); // NOI18N

        lbPrecioCompraParcela.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lbPrecioCompraParcela.setForeground(new java.awt.Color(255, 255, 255));
        lbPrecioCompraParcela.setText("15");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda16.png"))); // NOI18N

        btnComprarParcela.setText("Comprar\n");
        btnComprarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarParcelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelComprarParcelaLayout = new javax.swing.GroupLayout(panelComprarParcela);
        panelComprarParcela.setLayout(panelComprarParcelaLayout);
        panelComprarParcelaLayout.setHorizontalGroup(
            panelComprarParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComprarParcelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelComprarParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComprarParcelaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(lbPrecioCompraParcela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComprarParcelaLayout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(panelComprarParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComprarParcelaLayout.createSequentialGroup()
                                .addComponent(lbDineroParcela)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComprarParcelaLayout.createSequentialGroup()
                                .addComponent(btnComprarParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        panelComprarParcelaLayout.setVerticalGroup(
            panelComprarParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComprarParcelaLayout.createSequentialGroup()
                .addComponent(lbDineroParcela)
                .addGroup(panelComprarParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComprarParcelaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(panelComprarParcelaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelComprarParcelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPrecioCompraParcela)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComprarParcela)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda.png"))); // NOI18N

        panelVenderTrigo.setBackground(new java.awt.Color(221, 151, 12));
        panelVenderTrigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbDineroTrigo.setForeground(new java.awt.Color(0, 0, 0));
        lbDineroTrigo.setText("TRIGO");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda16.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trigo.png"))); // NOI18N

        lbPrecioVentaTrigo.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lbPrecioVentaTrigo.setForeground(new java.awt.Color(255, 255, 255));
        lbPrecioVentaTrigo.setText("2");

        btnVenderTrigo.setText("Vender\n");
        btnVenderTrigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderTrigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVenderTrigoLayout = new javax.swing.GroupLayout(panelVenderTrigo);
        panelVenderTrigo.setLayout(panelVenderTrigoLayout);
        panelVenderTrigoLayout.setHorizontalGroup(
            panelVenderTrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVenderTrigoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbDineroTrigo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelVenderTrigoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelVenderTrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVenderTrigoLayout.createSequentialGroup()
                        .addComponent(btnVenderTrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(panelVenderTrigoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbPrecioVentaTrigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        panelVenderTrigoLayout.setVerticalGroup(
            panelVenderTrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVenderTrigoLayout.createSequentialGroup()
                .addComponent(lbDineroTrigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVenderTrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecioVentaTrigo)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVenderTrigo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVenderSoja.setBackground(new java.awt.Color(221, 151, 12));
        panelVenderSoja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbDineroSoja.setForeground(new java.awt.Color(0, 0, 0));
        lbDineroSoja.setText("SOJA");

        btnVenderSoja.setText("Vender\n");
        btnVenderSoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderSojaActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soja.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/moneda16.png"))); // NOI18N

        lbPrecioVentaSoja.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lbPrecioVentaSoja.setForeground(new java.awt.Color(255, 255, 255));
        lbPrecioVentaSoja.setText("3");

        javax.swing.GroupLayout panelVenderSojaLayout = new javax.swing.GroupLayout(panelVenderSoja);
        panelVenderSoja.setLayout(panelVenderSojaLayout);
        panelVenderSojaLayout.setHorizontalGroup(
            panelVenderSojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVenderSojaLayout.createSequentialGroup()
                .addGroup(panelVenderSojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVenderSojaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVenderSoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelVenderSojaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(lbPrecioVentaSoja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVenderSojaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDineroSoja)
                .addGap(49, 49, 49))
        );
        panelVenderSojaLayout.setVerticalGroup(
            panelVenderSojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVenderSojaLayout.createSequentialGroup()
                .addComponent(lbDineroSoja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVenderSojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(lbPrecioVentaSoja))
                .addComponent(btnVenderSoja)
                .addGap(7, 7, 7))
        );

        panelProductos.setBackground(new java.awt.Color(105, 93, 64));
        panelProductos.setForeground(new java.awt.Color(51, 204, 255));

        lbIconoTrigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trigo.png"))); // NOI18N
        lbIconoTrigo.setText(" ");

        lbNumTrigo.setBackground(new java.awt.Color(255, 255, 255));
        lbNumTrigo.setFont(new java.awt.Font("Loma", 0, 24)); // NOI18N
        lbNumTrigo.setText("0\n");

        lbNumSoja.setBackground(new java.awt.Color(255, 255, 255));
        lbNumSoja.setFont(new java.awt.Font("Loma", 0, 24)); // NOI18N
        lbNumSoja.setText("0\n");

        lbIconoSoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/soja.png"))); // NOI18N
        lbIconoSoja.setText(" ");

        pbExp.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N

        lbNumLevelsExp.setText("0/3");

        lbIconExp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exp.png"))); // NOI18N

        lbExp.setText("NIVEL:");

        lbNumExp.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lbNumExp.setForeground(new java.awt.Color(51, 204, 255));
        lbNumExp.setText("1");

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbIconoTrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNumTrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbIconoSoja, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNumSoja, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(lbExp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNumExp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbIconExp))
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(lbNumLevelsExp)))
                .addContainerGap(448, Short.MAX_VALUE))
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                        .addComponent(lbNumLevelsExp)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbNumExp)
                                        .addComponent(lbExp))
                                    .addComponent(lbIconExp, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(11, 11, 11))
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pbExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbIconoTrigo)
                            .addComponent(lbNumTrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbIconoSoja)
                            .addComponent(lbNumSoja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
        );

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addComponent(lbLogoHayDay, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelComprarParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelVenderTrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelVenderSoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(panelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCabeceraLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLogoHayDay, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panelVenderSoja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelComprarParcela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelVenderTrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41)))
                .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMapa.setBackground(new java.awt.Color(153, 153, 153));
        panelMapa.setLayout(new java.awt.GridLayout(1, 0));

        lbHierba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHierba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapa.jpg"))); // NOI18N
        lbHierba.setOpaque(true);
        panelMapa.add(lbHierba);

        javax.swing.GroupLayout panelCampoLayout = new javax.swing.GroupLayout(panelCampo);
        panelCampo.setLayout(panelCampoLayout);
        panelCampoLayout.setHorizontalGroup(
            panelCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCampoLayout.setVerticalGroup(
            panelCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampoLayout.createSequentialGroup()
                .addComponent(panelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarParcelaActionPerformed
        Parcela nuevaParcela = new Parcela();
        addParcela(nuevaParcela);
        Controlador.instancia.comprar(nuevaParcela);
        actualizarVista(); // actualizarVista despues de comprar
    }//GEN-LAST:event_btnComprarParcelaActionPerformed
    
    private void btnVenderSojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderSojaActionPerformed
        Controlador.instancia.vender(TipoCultivo.SOJA);
        actualizarVista();
    }//GEN-LAST:event_btnVenderSojaActionPerformed

    private void btnVenderTrigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderTrigoActionPerformed
        Controlador.instancia.vender(TipoCultivo.TRIGO);
        actualizarVista();
    }//GEN-LAST:event_btnVenderTrigoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarParcela;
    private javax.swing.JButton btnVenderSoja;
    private javax.swing.JButton btnVenderTrigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbDinero;
    private javax.swing.JLabel lbDineroParcela;
    private javax.swing.JLabel lbDineroSoja;
    private javax.swing.JLabel lbDineroTrigo;
    private javax.swing.JLabel lbExp;
    private javax.swing.JLabel lbHierba;
    private javax.swing.JLabel lbIconExp;
    private javax.swing.JLabel lbIconoSoja;
    private javax.swing.JLabel lbIconoTrigo;
    private javax.swing.JLabel lbLogoHayDay;
    private javax.swing.JLabel lbNumExp;
    private javax.swing.JLabel lbNumLevelsExp;
    private javax.swing.JLabel lbNumSoja;
    private javax.swing.JLabel lbNumTrigo;
    private javax.swing.JLabel lbPrecioCompraParcela;
    private javax.swing.JLabel lbPrecioVentaSoja;
    private javax.swing.JLabel lbPrecioVentaTrigo;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelCampo;
    private javax.swing.JPanel panelComprarParcela;
    private javax.swing.JPanel panelMapa;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelVenderSoja;
    private javax.swing.JPanel panelVenderTrigo;
    private javax.swing.JProgressBar pbExp;
    // End of variables declaration//GEN-END:variables
}
