
package vista;

import controlador.Controlador;
import javax.swing.JPanel;
import modelo.Colada;
import modelo.Fajana;
import modelo.Fenomeno;
import modelo.Volcan;


/**
 *
 * @author angel_rodriguez
 */
public class Vista extends javax.swing.JFrame {
    private Controlador controlador;

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lbFenomeno = new javax.swing.JLabel();
        lbVolcan1 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        tfFenomeno = new javax.swing.JTextField();
        tfVolcan = new javax.swing.JTextField();
        tfTipo = new javax.swing.JTextField();
        lbTipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        lbFenomeno.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        lbFenomeno.setForeground(new java.awt.Color(0, 0, 0));
        lbFenomeno.setText("Fenómeno:");

        lbVolcan1.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        lbVolcan1.setForeground(new java.awt.Color(0, 0, 0));
        lbVolcan1.setText("Volcán: ");

        btnSiguiente.setBackground(new java.awt.Color(166, 204, 255));
        btnSiguiente.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(0, 0, 0));
        btnSiguiente.setText("Siguiente Fenómeno ");
        btnSiguiente.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 102), new java.awt.Color(176, 238, 255)));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        tfFenomeno.setBackground(new java.awt.Color(204, 204, 204));
        tfFenomeno.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        tfFenomeno.setForeground(new java.awt.Color(0, 0, 0));

        tfVolcan.setBackground(new java.awt.Color(204, 204, 204));
        tfVolcan.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        tfVolcan.setForeground(new java.awt.Color(0, 0, 0));
        tfVolcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVolcanActionPerformed(evt);
            }
        });

        tfTipo.setBackground(new java.awt.Color(204, 204, 204));
        tfTipo.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        tfTipo.setForeground(new java.awt.Color(0, 0, 0));

        lbTipo.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        lbTipo.setForeground(new java.awt.Color(0, 0, 0));
        lbTipo.setText("Tipo:");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lbVolcan1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfVolcan, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lbFenomeno, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFenomeno, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVolcan1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVolcan))
                .addGap(27, 27, 27)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFenomeno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFenomeno)
                    .addComponent(tfTipo)
                    .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        controlador.siguiente();        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void tfVolcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVolcanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVolcanActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel lbFenomeno;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbVolcan1;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField tfFenomeno;
    private javax.swing.JTextField tfTipo;
    private javax.swing.JTextField tfVolcan;
    // End of variables declaration//GEN-END:variables

    public void actualizarVista(Volcan volcan, Fenomeno fenomeno){
        String tipoFenomeno = fenomeno.getClass().getSimpleName();
        this.tfVolcan.setText(volcan.getNombre());
        this.tfFenomeno.setText(tipoFenomeno + ": " + fenomeno.getNombre());
        this.tfTipo.setText(tipoFenomeno);
        
        repaint();
        revalidate();
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    
    
}
